###
GET http://localhost:6066/api/res


###
GET http://localhost:6066/api/res/


###
POST http://localhost:6066/api/res
Content-type: application/json

{
    "restaurantName": "Burger King",
    "location":{
        "type": "Point",
        "coordinates": [47.923069578085475, 106.93432584092422]
    }
}

###
POST http://localhost:6066/api/nearRes
Content-type: application/json

{
    "lat":47.92374108411315,
    "long":106.93352863307179
}
